name: Doc

env: 
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  push:
    branches: [ master ]
  
jobs:
  build: 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: septotrip.com
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker-compose -f docker-compose.prod.yml pull doc
          docker-compose -f docker-compose.prod.yml stop doc
          docker-compose -f docker-compose.prod.yml rm -f doc
          docker-compose -f docker-compose.prod.yml --env-file ./.env up -d doc